### ISSUE TITLE
follow job failure

### ISSUE THREAD

**Issue by liuyijiang1994** [asukaonly/weibo-lottery#1]
10:40:38.719 logback [pool-3-thread-1] INFO  com.miaomiao.service.WeiboService - 549270875@qq.com Login Success, Cookies: [********************隐藏掉], Time: Thu Dec 21 10:40:38 CST 2017
10:40:38.858 logback [pool-3-thread-1] WARN  o.a.h.c.p.ResponseProcessCookies - Cookie rejected [U_TRS1="0000005b.6a152b1f.5a3b1f26.96fbdba7", version:0, domain:sina.com.cn, path:/, expiry:Sun Dec 19 10:40:38 CST 2027] Illegal 'domain' attribute "sina.com.cn". Domain of origin: "s.weibo.com"
10:40:38.859 logback [pool-3-thread-1] WARN  o.a.h.c.p.ResponseProcessCookies - Cookie rejected [U_TRS2="0000005b.6a2a2b1f.5a3b1f26.68a84e9a", version:0, domain:sina.com.cn, path:/, expiry:null] Illegal 'domain' attribute "sina.com.cn". Domain of origin: "s.weibo.com"
10:40:38.862 logback [pool-3-thread-1] INFO  com.miaomiao.service.WeiboService - Mid:4187342632022739 End Follow Job, Status: failed, time:Thu Dec 21 10:40:38 CST 2017

**Comment by asukaonly** [comment]
m端登陆的cookies有点问题，现在已经修复了
